### ISSUE TITLE
Write a simple README.md

### ISSUE THREAD

**Issue by ghost** [OpenFloodAI/OpenFloodAI#1]
Write a simple **README.md** about how to contribute to [openfloodai.github.io](https://github.com/OpenFloodAI/openfloodai.github.io)
add all the steps (from finding an issue, forking the repository to sending PR!)

**Note: make it attractive**

**Comment by Sweta271097** [comment]
@adventuroussrv Can I work on this issue?

**Comment by ghost** [comment]
Sure, @Sweta271097 I have assigned you!

**Comment by Sweta271097** [comment]
@adventuroussrv Thanks. I'm on it.

**Comment by ghost** [comment]
Awesome @Sweta271097! go ahead, Will be waiting for your PR!
