### ISSUE TITLE
add social media links to README 

### ISSUE THREAD

**Issue by ghost** [OpenFloodAI/OpenFloodAI#4]
**Twitter:**        https://twitter.com/OpenFloodAI
**Facebook:**    https://www.facebook.com/OpenFloodAI
**website:**       https://openfloodai.github.io

**Comment by PraneshUlleri** [comment]
Can I work on it?

**Comment by ghost** [comment]
Sure, @PraneshUlleri

**Comment by shogunzalo** [comment]
Done
